# Generated by Django 3.2.4 on 2021-07-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ip', models.CharField(db_index=True, max_length=30, null=True)),
                ('hostname', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(db_index=True, max_length=50, null=True)),
                ('region', models.CharField(db_index=True, max_length=50, null=True)),
                ('country', models.CharField(db_index=True, max_length=50, null=True)),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
                ('org', models.CharField(max_length=50, null=True)),
                ('timezone', models.CharField(db_index=True, max_length=50, null=True)),
                ('country_name', models.CharField(db_index=True, max_length=50, null=True)),
                ('browser', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('os', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('device', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('is_bot', models.BooleanField(null=True)),
                ('is_email_client', models.BooleanField(null=True)),
                ('is_pc', models.BooleanField(null=True)),
                ('is_tablet', models.BooleanField(null=True)),
                ('is_mobile', models.BooleanField(null=True)),
                ('is_touch_capable', models.BooleanField(null=True)),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='short.urls')),
            ],
        ),
    ]
