# Generated by Django 3.2.4 on 2021-07-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_statsurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsurl',
            name='url_key',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
