# Generated by Django 3.2.4 on 2021-07-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0003_alter_statsurl_url_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsurl',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
