# Generated by Django 3.2.4 on 2021-07-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0004_alter_statsurl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsurl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
