# Generated by Django 3.2.4 on 2021-07-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0005_alter_statsurl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsurl',
            name='browser',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statsurl',
            name='device',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statsurl',
            name='os',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
