# Generated by Django 3.2.4 on 2021-07-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0007_auto_20210726_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
